BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'

        TextInput:
            id: input_number
            text: '10'
            font_size: 48
            multiline: False
        BoxLayout:
            orientation:'vertical'
            Button:             #up
                text: "Up"

            Button:             #down
                text: "Down"
